#Web服务器：apache | nginx，通过交互式选择获取
joomla_webs: apache

joomla_vhost_dir: /etc/httpd/vhost
joomla_vhost_src: vhost.conf
joomla_service: httpd
joomla_owner: apache
joomla_db_password: "123456"
joomla_name: "joomla"
joomla_title: "Joomla"
#下载链接需定期维护
joomla_download_url: "https://github.com/joomla/joomla-cms/releases/download/3.9.21/Joomla_3.9.21-Stable-Full_Package.zip"

